image: docker
services:
  - docker:dind

stages:
  - test
  - deploy staging
  - deploy production

test:
  stage: test
  tags: 
    - stag
  only:
    - master
    - staging
  variables:
    DB_DRIVER: "mysql" 
  script:
    - npm install
    - npm test


deploy-staging:
  stage: deploy staging
  tags: 
    - stag
  only:
    - staging
  script:
    - sudo docker-compose -v
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build --build-arg ENV=stag
    - sudo docker-compose -f docker-compose.yml up -d

deploy-production:
  stage: deploy production
  tags: 
    - prod
  only:
    - master
  script:
    - sudo docker-compose -v
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build--build-arg ENV=prod
    - sudo docker-compose -f docker-compose.yml up -d
    
  when: manual  
  
