image: docker
services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - dev
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  only:
    - dev
  script:
    - sudo docker image prune -f
    - sudo docker-compose --version
    - sudo docker-compose build
    - sudo docker-compose up -d
