version: '3.2'

services:
    skeleton_proxy_sql:
      container_name: 'skeleton_sql'
      build: 
        context: .
        dockerfile: proxysql-dockerfile
      ports:
        - 4001:6032
        - 4002:6033
      restart: always


    skeleton_redis:
      container_name: 'skeleton_redis'
      image: redis:alpine
      ports:
        - 4003:6379
      restart: always

      
    skeleton_app:
      container_name: 'skeleton'
      build: .
      links:
        - "skeleton_proxy_sql"
        - "skeleton_redis"
      depends_on:
        - "skeleton_proxy_sql"
        - "skeleton_redis"
      ports:
        - 4000:3000
      restart: always
