version: '3'

services:
    db:
      container_name: 'skeleton_db'
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'skeleton'
        MYSQL_USER: 'skeleton'
        MYSQL_PASSWORD: '1'
        MYSQL_ROOT_PASSWORD: '1'
      ports:
        - 4001:3306
      restart: always
    redis:
      container_name: 'skeleton_redis'
      image: redis:alpine
      ports:
        - 4002:6379
      restart: always
    app:
      container_name: 'skeleton'
      build: .
      links:
        - "db"
      depends_on:
        - "db"
      ports:
        - 4000:3000
      restart: always